disabled_rules:
  - todo
  - trailing_whitespace
  - force_cast
  - force_try
opt_in_rules:
  - array_init
  - attributes
  - closure_spacing
  - explicit_init
  - first_where
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - vertical_parameter_alignment_on_call
  - yoda_condition
line_length:
  warning: 140
  error: 240
file_length:
  warning: 1200
  error: 3000
type_body_length:
  warning: 500
  error: 900
identifier_name:
  min_length: 2
  max_length:
    warning: 48
    error: 60
excluded:
  - .build
  - build
  - DerivedData
